### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by GabrielCrocker7** [Shiina001/BombBot#1]
I was just wondering what pip packages to install.

**Comment by Shiina001** [comment]
just selenium


niedz., 8 sie 2021 o 02:01 GabrielCrocker7 ***@***.***>
napisał(a):

**Comment by Shiina001** [comment]
Bot is not still finished and i will be working to make it more user friendly :)

**Comment by GabrielCrocker7** [comment]
k thanks bro
